name: vhs
on:
  push:
    paths:
      - vhs.tape
      - .github/workflows/vhs.yml

permissions:
  contents: write

jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Build
        run: |
          sudo go build -o /usr/local/bin/bb main.go
          /usr/local/bin/bb -h
          pwd
      - uses: charmbracelet/vhs-action@v2
        with:
          path: 'vhs.tape'
      - uses: stefanzweifel/git-auto-commit-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated VHS GIF
          branch: main
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: '*.gif'